In [ ]:
# Numpy is python library written in C language for working and processing arrays.

In [ ]:
# Python Data Science Handbook: p 33 - 96

In [ ]:
# Usually it calls C or CPython code for a faster processing of arrays.

In [1]:
# So, to start working wiht numpy we must firstly import it
import numpy as np

In [ ]:
# Let's firstly generate 3 random arrays: a vector, a matrix and a tensor

In [2]:
# Setting up the seed
np.random.seed(42)

vector = np.random.randint(10, size=6)
matrix = np.random.randint(10, size = (3, 4))
tensor = np.random.randint(10, size = (3, 4 , 5))

In [3]:
matrix

array([[2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])

In [4]:
# ndim - returns the number of dimensions of the array
print(f'vector - {vector.ndim}')
print(f'matrix - {matrix.ndim}')
print(f'tensor - {tensor.ndim}')

vector - 1
matrix - 2
tensor - 3


In [ ]:
# shape - returhs the shape of the array
print(f'vector - {vector.shape}')
print(f'matrix - {matrix.shape}')
print(f'tensor - {tensor.shape}')

vector - (6,)
matrix - (3, 4)
tensor - (3, 4, 5)


In [ ]:
# size = returns the number of elements in the array
print(f'vector - {vector.size}')
print(f'matrix - {matrix.size}')
print(f'tensor - {tensor.size}')

vector - 6
matrix - 12
tensor - 60


In [ ]:
# Looking at the data type
vector.dtype

dtype('int32')

In [ ]:
# ARRAY INDEXATION

In [ ]:
# To get an element from an array we must us indexes. Indexes start at 0, and they represent
# the number of steps that must be taken from the beggining of the array to get an element.

In [ ]:
vector[0]

6

In [ ]:
matrix[0]

array([2, 6, 7, 4])

In [ ]:
tensor[0]

array([[5, 1, 4, 0, 9],
       [5, 8, 0, 9, 2],
       [6, 3, 8, 2, 4],
       [2, 6, 4, 8, 6]])

In [ ]:
# To get an element from an array with more dimensions than one we must use more indexes

In [ ]:
matrix[0][1]

6

In [ ]:
tensor[0][1]

array([5, 8, 0, 9, 2])

In [ ]:
tensor[0][1][4]

2

In [ ]:
# USING SLICES TO GET MORE ELEMENTS.

In [ ]:
# Getting the first 3 elements of the array
vector[:3]

array([6, 3, 7])

In [ ]:
# Getting the last 3 elemetns
vector[3:]

array([4, 6, 9])

In [ ]:
# Getting all every 2 element
vector[::2]

array([6, 7, 6])

In [ ]:
# In matrices and tensors we can use slices to get the value of only some columns of rows

In [4]:
# For exemple let's get only the even column
matrix[:, ::2]

array([[2, 7],
       [3, 7],
       [5, 1]])

In [5]:
# Or only the first half of columns
matrix[:, :3]

array([[2, 6, 7],
       [3, 7, 7],
       [5, 4, 1]])

In [ ]:
# Changing the values in an array.
vector[1] = 99
vector

array([ 6, 99,  7,  4,  6,  9])

In [ ]:
# also we can change more vlues using slices
matrix[:, 0] = np.zeros(3)

In [ ]:
matrix

array([[0, 6, 7, 4],
       [0, 7, 7, 2],
       [0, 4, 1, 7]])

In [ ]:
# np.zeros and np.ones allows to create arrays with zeros or only with ones

In [ ]:
# Let's create a zero filled vector.
np.zeros(3)

array([0., 0., 0.])

In [ ]:
# If we will pass tuple of values the function will create an array with more dimensions
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# By the same logic works and the np.ones functions.
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
# The same will take place if we will pass a tuple.
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# CREATION OF COPIES

In [ ]:
fake_copy = vector

In [ ]:
# Let's verify their ids, or memory adresses
print(id(fake_copy))
print(id(vector))

2040425261536
2040425261536


In [ ]:
# They are pointing to the same memory cell.

In [ ]:
# So this is a fake copy, to create a real one copy, we should use the copy function
real_copy = vector.copy()

In [ ]:
print(id(real_copy))
print(id(vector))

2040439290816
2040425261536


In [ ]:
# Now le's see the difference.

In [ ]:
print(vector)
print(fake_copy)
print(real_copy)

[0 8 6 8 7 0]
[0 8 6 8 7 0]
[0 8 6 8 7 0]


In [ ]:
# Let's change the vector and see what happens
vector[0] = 99

In [ ]:
print(vector)
print(fake_copy)
print(real_copy)

[99  8  6  8  7  0]
[99  8  6  8  7  0]
[0 8 6 8 7 0]


In [ ]:
# As you can see the fake_copy array also changed itself.

In [ ]:
# This happens because in python variables aren't boxes but stickers to boxes.
# Meaning that by creatting a fake copy you are just sticking another sticker to a box.

In [ ]:
# CONCATENATION AND SPLITTING

In [ ]:
# Concatenation means sticking of 2 or more arrays in one.

In [10]:
x1 = np.array([1, 2, 3])
x2 = np.array([4, 5, 6])
np.concatenate([x1, x2])

array([1, 2, 3, 4, 5, 6])

In [11]:
x1 = np.ones(10)

In [12]:
x1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
x1.reshape(5, 2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
x1.shape

(3,)

In [ ]:
# Also we can concatenate 2d arrays

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
np.concatenate([matrix, matrix])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
np.concatenate([matrix, matrix])

array([[2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7],
       [2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])

In [ ]:
# Axis is saying to the function on which axis to concatenate.
# axis = 1 - means the columns.
# axis = 0 = means on the rows.

In [ ]:
# VSTACK AND HSTACK
# are used to stack arrays.

In [ ]:
# vstack is used to stack vertically arrays.
x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6],
                 [7, 8, 9]])
np.vstack([x, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# hstack is used to stack horizontally arrays.
x = np.array([[99],
              [99]])
np.hstack([x, grid])

array([[99,  4,  5,  6],
       [99,  7,  8,  9]])

In [ ]:
# split, hsplit and vsplit

In [ ]:
# np.split allows you to split an array into some ambount of parts
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
first, second = np.split(x, [5])

In [ ]:
first

array([1, 2, 3, 4, 5])

In [ ]:
second

array([ 6,  7,  8,  9, 10])

In [20]:
# hsplit and vsplit
matrix = np.arange(16).reshape((4, 4))
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

range(0, 10)

In [ ]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(matrix, [2])

In [ ]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
left, right = np.hsplit(matrix, [2])

In [ ]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [ ]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])