In [2]:
# Operations on vectors and matrices with numpy dot product, inversation, Transmutation

In [ ]:
# Python Data Science Handbook: p 91 - 97

In [3]:
# Usually python isn't the fastest programming language. In most of the times, this is because
# the dynamic typization and because of cycles, becouse they take more time to be interpreted.

In [4]:
# Let's see an example and compare pure python and the numpy one.
# Suppose we have an array of value, and we want to compute the inverse of every element.

In [5]:
import numpy as np
np.random.seed(42)

def compute_inverse(values):
    out = np.empty(len(values))
    for i in range(len(values)):
        out[i] = 1.0 / values[i]
    return out

values = np.random.randint(1, 10, size=5)
compute_inverse(values)

array([0.14285714, 0.25      , 0.125     , 0.2       , 0.14285714])

In [6]:
# Now let's create a big array, suppose with 1_000_000 values, and se how much it takes to 
# compute the inverse

In [7]:
big_array = np.random.randint(1, 100, size=1_000_000)

In [8]:
%%timeit -n 1 -r 1
compute_inverse(big_array)

2.36 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [9]:
# 2.3 seconds, now let's see how to do this wiht numpy
print(1.0 / big_array)

[0.01204819 0.01149425 0.01333333 ... 0.03571429 0.01086957 0.03225806]


In [10]:
%%timeit -n 1 -r 1
1.0 / big_array

6.66 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [11]:
# 7 ms quite a good rezult

In [12]:
# The lesson - always use if possible numpy array when working with data.

In [13]:
# ARITHMETIC FUNCTIONS WITH SCALARS

In [3]:
x = np.arange(10)

In [15]:
# Addition
x + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
# substraction
x - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [17]:
# multiplication
x * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [18]:
# division
x / 4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [19]:
# floor_division
x // 4

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2], dtype=int32)

In [20]:
# power
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [21]:
# mod
x % 3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [8]:
# Also every arithmetic function is implimented in numpy
np.add(x, 2j)

array([0.+2.j, 1.+2.j, 2.+2.j, 3.+2.j, 4.+2.j, 5.+2.j, 6.+2.j, 7.+2.j,
       8.+2.j, 9.+2.j])

In [23]:
np.subtract(x, 2)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [24]:
np.multiply(x, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.divide(x, 2)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [26]:
np.floor_divide(x, 2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [27]:
np.power(x, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [28]:
np.mod(x, 2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [29]:
# absolute value
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [30]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [31]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [32]:
# reduce

In [33]:
# Python has a special function named reduce, it allows to apply a 2-entry function on
# a list of values.

In [34]:
# Numpy has it's own version of reduce. or more corectly versions.

In [35]:
# For example let's find out the factorial of a number using reduce.

In [9]:
values = np.arange(1, 6)

In [10]:
values

array([1, 2, 3, 4, 5])

In [11]:
fact = np.add.reduce(values)

In [12]:
fact

15

In [40]:
# Acumulate function - allows to get all intermediate results of the reduce function.

In [41]:
np.multiply.accumulate(values)

array([  1,   2,   6,  24, 120], dtype=int32)

In [42]:
# As you can see there are all velues.

In [43]:
# AGGREGATION FUNCTIONS

In [46]:
# sum
x = np.random.random(100)
np.sum(x)

56.25353782156944

In [47]:
x

array([0.62996299, 0.78813257, 0.77197926, 0.40986389, 0.39628163,
       0.52423788, 0.93653808, 0.92390734, 0.82179513, 0.34197489,
       0.62552038, 0.18740148, 0.81954089, 0.85022226, 0.82029172,
       0.07664023, 0.69509512, 0.96667015, 0.97263794, 0.20196514,
       0.56996077, 0.7430693 , 0.00807013, 0.74646871, 0.84759639,
       0.73193857, 0.9144088 , 0.74223535, 0.66449479, 0.59714074,
       0.63841489, 0.23393245, 0.01437578, 0.81729764, 0.39720246,
       0.75895708, 0.02193517, 0.60424732, 0.62870144, 0.18052245,
       0.21055593, 0.67582688, 0.7536605 , 0.20525403, 0.55976654,
       0.41898458, 0.22099382, 0.76362914, 0.74071963, 0.14201163,
       0.2870598 , 0.28932619, 0.13792843, 0.46585296, 0.64839625,
       0.93885893, 0.77101923, 0.47272569, 0.45545493, 0.2709066 ,
       0.40516306, 0.32798419, 0.65354013, 0.93661894, 0.83406224,
       0.56254556, 0.75712459, 0.88853693, 0.94246305, 0.90809787,
       0.30829823, 0.07541285, 0.45684936, 0.45911108, 0.98387

In [48]:
# min
np.min(x)

0.008070131761300448

In [49]:
# max
np.max(x)

0.9924369280116836

In [15]:
# Generation of a matrix
x2 = np.random.random((5, 2))
x2

array([[0.65312804, 0.41870655],
       [0.06283207, 0.40942776],
       [0.65825487, 0.8089632 ],
       [0.60663405, 0.583341  ],
       [0.04285369, 0.49669871]])

In [25]:
# Finding the minimal value for every row
x2.prod(axis=0)

array([0.00070225, 0.04018198])

In [59]:
# Finding the minimal value for every column
x2.min(axis=0)

array([0.11353877, 0.14486956])

In [60]:
# TRANSLATION

In [61]:
# Numpy has some special rules for working with pairs of arrays.
# Let's beggin with an example

In [62]:
a = np.array([1, 2, 3])
b = np.array([5, 6, 7])
a + b

array([ 6,  8, 10])

In [63]:
# It was simple

In [29]:
# Now let's see another example.
matrix = np.ones((3, 3))
matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
matrix + a

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [26]:
x = np.array([1, 2, 3]).reshape(3, 1)

In [27]:
x

array([[1],
       [2],
       [3]])

In [31]:
matrix + x

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [66]:
# As you see the vector 'a' was added to every row of the matrix

In [67]:
# It also was simple, now let's dive even deeper.

In [35]:
a = np.arange(4)
b = np.arange(4)[:, np.newaxis]

In [36]:
a

array([0, 1, 2, 3])

In [37]:
b

array([[0],
       [1],
       [2],
       [3]])

In [38]:
a + b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [72]:
# Dot product

In [73]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [40]:
a = np.array([1, 2, 3])

matrix = np.array([[1, 3, 4],
                [4, 5, 6]])
np.dot(matrix, a)

array([19, 32])