In [1]:
# 3 Copmuting the determinand with numpy, Inversation, Transmutation

In [ ]:
# Python Data Science Handbook: p 58 - 128

In [3]:
# So, finding the determinant in numpy is a very easy task, let's look how to do that.

In [1]:
import numpy as np

In [2]:
matrix = np.random.random((4, 4))

In [3]:
matrix

array([[0.45904312, 0.12720518, 0.90875149, 0.55226184],
       [0.62759372, 0.29598661, 0.88919016, 0.01855239],
       [0.05667402, 0.66335804, 0.13766663, 0.87011566],
       [0.09330723, 0.33371825, 0.7015403 , 0.57197272]])

In [11]:
# The determinant function in numpy is stored in a special submodule, named linalg
# it stores all function related to linear algebra

In [4]:
np.linalg.det(matrix)

-0.12483488287994002

In [13]:
# As you see it is very simple.

In [14]:
# Next let's see how to calcutate the inverse of a matrix.

In [5]:
np.linalg.inv(matrix)

array([[ 1.83258325,  0.66551473,  1.07649617, -3.42864055],
       [-2.32156126,  1.48098587,  0.80253394,  0.97266266],
       [-0.55693719,  0.18699626, -1.04012005,  2.11396564],
       [ 1.73866327, -1.20200621,  0.63188509, -0.85268123]])

In [16]:
# And the Transpose of the matrix.

In [17]:
matrix.T

array([[0.75190875, 0.46332178, 0.83469728, 0.73011852],
       [0.88232505, 0.48904152, 0.12434692, 0.96606518],
       [0.061924  , 0.66219779, 0.31473953, 0.06137767],
       [0.22234182, 0.77498191, 0.70661784, 0.6370885 ]])

In [18]:
# We can find the Transpose of the matrix even if it isn't square

In [19]:
matrix = np.random.random((3, 4))

In [20]:
matrix

array([[0.59241907, 0.147951  , 0.07066675, 0.70429706],
       [0.8878579 , 0.13505785, 0.06201879, 0.32860178],
       [0.09644889, 0.06541188, 0.9075991 , 0.38730681]])

In [21]:
matrix.T

array([[0.59241907, 0.8878579 , 0.09644889],
       [0.147951  , 0.13505785, 0.06541188],
       [0.07066675, 0.06201879, 0.9075991 ],
       [0.70429706, 0.32860178, 0.38730681]])